dist: focal

language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update

install:

# OpenCV install code
# with inputs from
# https://stackoverflow.com/questions/54531215/how-to-install-opencv-4-on-travis-ci
# and https://vegastack.com/tutorials/how-to-install-opencv-on-ubuntu-20-04/
  - sudo apt install build-essential cmake git pkg-config libgtk-3-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev python3-dev python3-numpy \
    libtbb2 libtbb-dev libdc1394-22-dev libopenexr-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev


script:
  - git clone https://github.com/opencv/opencv
  - git checkout -b 4.3.0
  - cd opencv
  - mkdir build
  - cd build
  - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D CMAKE_INSTALL_PREFIX=OpenCVLocal ..
  #- cat CMakeCache.txt | grep CPACK_BINARY_DEB
  - make -j2
  - make install
  - cd ../..
  
  - zip -r OpenCVbuild.zip /home/travis/build/hn-88/opencvdeb/opencv/build/OpenCVLocal
  
  # in case Github deploy fails
  #- curl --upload-file OpenCVbuild.zip https://transfer.sh/OpenCVbuild.zip
  # transfer.sh is down
  
deploy:
  provider: releases
  token: $mytokenname
  file_glob: true
  file: OpenCVbuild.zip
  draft: true
  edge: true
