# Building OpenCV 4.3.0 binaries for ease of building projects which use OpenCV 
version: 4.3.0.{build}
# base image
image: Visual Studio 2015

platform: Win32
configuration: Release       

install:
 - ps: Start-FileDownload https://github.com/opencv/opencv/archive/4.3.0.zip
 - 7z x 4.3.0.zip
 - cd opencv-4.3.0
 - cd modules\videoio\src
 - ps: Start-FileDownload https://github.com/hn-88/opencvpatch/raw/master/cap_dshow.cpp
 
 - cd ..\..\..
 - md build
 - cd build
 - cmake -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_world=ON -G "Visual Studio 14 2015" -A Win32 ..
 - cmake --build .  --config release
 - cmake --build .  --target install --config release
 - cd ..
 - cd .. 
 - cmd: setx -m OpenCV_DIR C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14
 - cmd: setx path "%path%;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\bin;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\lib"
 - refreshenv
  
  
#build:
#  project: OCVWarpWin32.vcxproj

#  verbosity: minimal
 
artifacts:
- path: opencv-4.3.0\build\install\x86\vc14\bin\*.dll
  name: OpenCV dlls
    
